name: Rust

on:
 workflow_dispatch:
 push:
  paths:
    - 'src/**'
  branches: [ main ]
 pull_request:
  branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  DISCORD_TOKEN: token

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
