name: Build

on:
 workflow_dispatch:
 push:
  paths:
    - 'src/**'
  branches: [ main ]
 pull_request:
  branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  DISCORD_TOKEN: token

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
       override: true
       toolchain: nightly
    - run: cargo build
    - run: cargo test --verbose